kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: devops-fusion-sample-pipeline
spec:
  source:
    git:
      uri: https://github.com/KonCarmine/workshop.git
      ref: without_prod_template
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfile.groovy
      env:
      - name: OPENSHIFT_NAMESPACE
        value: konplancarminetest
    type: JenkinsPipeline